package bz.nationalbus.nbc;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Bitmap;
import android.graphics.drawable.GradientDrawable;
import android.os.Build;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowInsets;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.text.SimpleDateFormat;
import java.util.*;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.common.BitMatrix;

public class MainActivity extends Activity {
    private final int NAVY=Color.rgb(7,26,43), TEAL=Color.rgb(24,169,139), GOLD=Color.rgb(249,199,79), ICE=Color.rgb(244,248,248), MUTED=Color.rgb(91,107,120), LINE=Color.rgb(220,231,232);
    private ApiClient api; private LinearLayout content; private boolean ops; private boolean atRoot=true; private JSONObject capabilities=new JSONObject();
    private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private LinearLayout box(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);return x;}
    private TextView txt(String s,float size,int color){TextView x=new TextView(this);x.setText(s);x.setTextSize(size);x.setTextColor(color);x.setPadding(0,dp(3),0,dp(3));return x;}
    private TextView h1(String s){TextView x=txt(s,25,NAVY);x.setTypeface(null,1);return x;}
    private TextView small(String s){return txt(s,14,MUTED);}
    private Button btn(String s,boolean primary){Button x=new Button(this);x.setText(s);x.setTextSize(14);x.setAllCaps(false);x.setTypeface(null,1);x.setTextColor(primary?Color.WHITE:TEAL);x.setMinHeight(dp(48));x.setPadding(dp(14),0,dp(14),0);x.setBackgroundResource(primary?R.drawable.primary_button:R.drawable.secondary_button);return x;}
    private EditText field(String hint){EditText x=new EditText(this);x.setHint(hint);x.setTextSize(16);x.setSingleLine(true);x.setTextColor(NAVY);x.setHintTextColor(MUTED);x.setBackgroundResource(R.drawable.rounded_input);x.setPadding(dp(14),0,dp(14),0);return x;}
    private void add(View x){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=dp(12);content.addView(x,p);}
    private void spacer(){Space x=new Space(this);content.addView(x,new LinearLayout.LayoutParams(1,dp(8)));}
    private LinearLayout card(){LinearLayout x=box();x.setPadding(dp(16),dp(14),dp(16),dp(14));x.setBackgroundResource(R.drawable.rounded_card);return x;}
    private LinearLayout tealCard(){LinearLayout x=box();x.setPadding(dp(16),dp(14),dp(16),dp(14));x.setBackgroundColor(TEAL);return x;}
    private void gap(LinearLayout x){Space s=new Space(this);x.addView(s,new LinearLayout.LayoutParams(1,dp(8)));}
    private String message(Exception e){return e==null||e.getMessage()==null?"Something went wrong":e.getMessage();}
    private void toast(String s){Toast.makeText(this,s==null?"Something went wrong":s,Toast.LENGTH_LONG).show();}
    private String today(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
    private JSONObject payload(Object... values){JSONObject p=new JSONObject();try{for(int i=0;i+1<values.length;i+=2)p.put(String.valueOf(values[i]),values[i+1]);}catch(Exception ignored){}return p;}
    private JSONObject resultObj(JSONObject r){JSONObject q=r.optJSONObject("result");return q==null?r:q;}
    private String objectName(JSONObject parent,String key,String fallback){JSONObject o=parent==null?null:parent.optJSONObject(key);return o==null?fallback:o.optString("name",fallback);}
    private String tripValue(JSONObject ticket,String key,String fallback){JSONObject trip=ticket==null?null:ticket.optJSONObject("trip");return trip==null?ticket.optString(key,fallback):trip.optString(key,ticket.optString(key,fallback));}
    private boolean allowed(String key){return capabilities.optBoolean(key,false);}

    @Override public void onCreate(Bundle b){super.onCreate(b);api=new ApiClient(this);ops=getPackageName().contains("operations");if(api.loggedIn())loadCapabilities(ops);else home();}
    private void shell(String title){
        atRoot=(ops&&"Operations".equals(title))||(!ops&&"NBC Traveler".equals(title));
        LinearLayout root=box();root.setBackgroundColor(ICE);LinearLayout bar=box();bar.setPadding(dp(20),dp(12),dp(20),dp(16));bar.setBackgroundColor(NAVY);
        LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);if(!atRoot){Button back=btn("‹",false);back.setTextColor(Color.WHITE);back.setTextSize(30);back.setBackgroundColor(Color.TRANSPARENT);back.setPadding(0,0,0,0);back.setOnClickListener(v->home());row.addView(back,new LinearLayout.LayoutParams(dp(38),dp(48)));}ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.nbc_logo);logo.setScaleType(ImageView.ScaleType.FIT_CENTER);row.addView(logo,new LinearLayout.LayoutParams(dp(48),dp(48)));
        LinearLayout names=box();TextView brand=txt("NATIONAL BUS",11,GOLD);brand.setTypeface(null,1);names.addView(brand);TextView page=txt(title,21,Color.WHITE);page.setTypeface(null,1);names.addView(page);row.addView(names,new LinearLayout.LayoutParams(0,-2,1));
        if(api.loggedIn()){Button out=btn("Sign out",false);out.setTextColor(Color.WHITE);out.setBackgroundColor(Color.TRANSPARENT);out.setOnClickListener(v->{api.logout();home();});row.addView(out,new LinearLayout.LayoutParams(dp(82),dp(44)));}bar.addView(row);root.addView(bar);
        ScrollView scroll=new ScrollView(this);content=box();content.setPadding(dp(20),dp(20),dp(20),dp(28));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=navBar();root.addView(nav,new LinearLayout.LayoutParams(-1,dp(70)));setContentView(root);
        root.setOnApplyWindowInsetsListener((v,insets)->{int bottom=Build.VERSION.SDK_INT>=30?insets.getInsets(WindowInsets.Type.navigationBars()).bottom:insets.getSystemWindowInsetBottom();nav.setPadding(dp(8),dp(5),dp(8),dp(5)+bottom);ViewGroup.LayoutParams lp=nav.getLayoutParams();lp.height=dp(70)+bottom;nav.setLayoutParams(lp);return insets;});root.requestApplyInsets();
    }
    private void authShell(boolean staff){
        atRoot=false;
        LinearLayout root=box();root.setBackgroundColor(ICE);LinearLayout hero=box();hero.setGravity(Gravity.CENTER);hero.setPadding(dp(24),dp(18),dp(24),dp(20));hero.setBackgroundResource(R.drawable.login_hero);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.nbc_logo);logo.setScaleType(ImageView.ScaleType.FIT_CENTER);hero.addView(logo,new LinearLayout.LayoutParams(dp(116),dp(132)));TextView n=txt("NATIONAL BUS COMPANY",14,GOLD);n.setTypeface(null,1);n.setGravity(Gravity.CENTER);hero.addView(n);TextView m=txt(staff?"OPERATIONS PORTAL":"PASSENGER APP",12,Color.WHITE);m.setGravity(Gravity.CENTER);hero.addView(m);root.addView(hero,new LinearLayout.LayoutParams(-1,dp(250)));ScrollView scroll=new ScrollView(this);content=box();content.setPadding(dp(22),dp(22),dp(22),dp(24));content.setBackgroundResource(R.drawable.auth_panel);scroll.addView(content);LinearLayout.LayoutParams panel=new LinearLayout.LayoutParams(-1,0,1);panel.setMargins(dp(14),dp(-8),dp(14),dp(14));root.addView(scroll,panel);TextView foot=txt("Secure access to NBC services",12,MUTED);foot.setGravity(Gravity.CENTER);root.addView(foot,new LinearLayout.LayoutParams(-1,dp(30)));setContentView(root);
    }
    private LinearLayout navBar(){LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.TOP);nav.setPadding(dp(8),dp(5),dp(8),dp(5));nav.setBackgroundColor(Color.WHITE);String[] labels=ops?new String[]{"⌂\nDashboard","▤\nRuns","✓\nScanner","▣\nMore"}:new String[]{"⌂\nHome","▣\nMy Trips","▤\nBoards","♙\nAccount"};View.OnClickListener[] clicks=ops?new View.OnClickListener[]{v->operationsHome(),v->runs(),v->scan(),v->operationsMore()}:new View.OnClickListener[]{v->passengerHome(),v->myTrips(),v->board(),v->account()};for(int i=0;i<labels.length;i++){Button b=btn(labels[i],false);b.setTextSize(12);b.setPadding(0,0,0,0);b.setTextColor(i==0?TEAL:MUTED);b.setBackgroundColor(Color.TRANSPARENT);b.setOnClickListener(clicks[i]);nav.addView(b,new LinearLayout.LayoutParams(0,dp(60),1));}return nav;}
    private void action(String icon,String title,String desc,View.OnClickListener click){LinearLayout c=card(),row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView i=txt(icon,25,TEAL);i.setGravity(Gravity.CENTER);row.addView(i,new LinearLayout.LayoutParams(dp(38),dp(42)));LinearLayout copy=box();TextView t=txt(title,17,NAVY);t.setTypeface(null,1);copy.addView(t);copy.addView(small(desc));row.addView(copy,new LinearLayout.LayoutParams(0,-2,1));c.addView(row);c.setOnClickListener(click);add(c);}
    private void home(){if(ops){if(api.loggedIn())operationsHome();else login(true);}else passengerHome();}

    @Override public void onBackPressed(){if(!atRoot){home();}else{super.onBackPressed();}}

    private void login(boolean staff){
        authShell(staff);add(h1(staff?"Staff sign in":"Welcome back, traveler."));
        add(small(staff?"Sign in with your NBC operations account.":"Sign in to view tickets and continue a booking."));
        EditText user=field("Email or username");
        EditText password=field("Password");password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);
        add(user);add(password);Button submit=btn("Sign in securely",true);add(submit);
        if(!staff){Button create=btn("Create an NBC account",false);add(create);create.setOnClickListener(v->signup());}
        submit.setOnClickListener(v->{
            String username=user.getText().toString().trim(),secret=password.getText().toString();
            if(username.isEmpty()||secret.isEmpty()){toast("Enter your username and password.");return;}
            submit.setEnabled(false);submit.setText("Signing in…");
            api.login(username,secret,new ApiClient.Callback(){
                public void done(JSONObject r){runOnUiThread(()->{
                    JSONObject result=r.optJSONObject("result");
                    if(result!=null&&result.optInt("uid",0)>0){loadCapabilities(staff);return;}
                    submit.setEnabled(true);submit.setText("Sign in securely");toast("The username or password is incorrect.");
                });}
                public void error(Exception e){runOnUiThread(()->{submit.setEnabled(true);submit.setText("Sign in securely");toast(message(e));});}
            });
        });
    }

    private void loadCapabilities(boolean staff){api.call("/api/nbc/v1/mobile/capabilities",new JSONObject(),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONObject source=resultObj(r);capabilities=source.optJSONObject("capabilities");if(capabilities==null)capabilities=new JSONObject();if(staff&&!allowed("operations")&&!allowed("station_sales")){api.logout();toast("This account does not have NBC Operations access.");login(true);return;}home();});}public void error(Exception e){runOnUiThread(()->{if(staff){api.logout();toast("Could not verify your NBC Operations role.");login(true);}else home();});}});}

    private void signup(){authShell(false);add(h1("Create your NBC account"));add(small("Your email becomes your sign-in and NBC creates your account number automatically."));EditText name=field("Full name"),email=field("Email address"),phone=field("Mobile phone"),password=field("Password - at least 8 characters");password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);add(name);add(email);add(phone);add(password);Button create=btn("Create account",true);add(create);Button existing=btn("I already have an account",false);add(existing);existing.setOnClickListener(v->login(false));create.setOnClickListener(v->{String n=name.getText().toString().trim(),e=email.getText().toString().trim().toLowerCase(Locale.US),p=phone.getText().toString().trim(),secret=password.getText().toString();if(n.length()<2||!e.contains("@")||secret.length()<8){toast("Enter your full name, a valid email, and a password of at least 8 characters.");return;}create.setEnabled(false);api.call("/api/nbc/v1/account/signup",payload("name",n,"email",e,"phone",p,"password",secret),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONObject source=resultObj(r);if(!source.optBoolean("ok",false)){create.setEnabled(true);toast(source.optString("message",source.optString("error","Account could not be created.")));return;}api.login(e,secret,new ApiClient.Callback(){public void done(JSONObject auth){runOnUiThread(()->account());}public void error(Exception ex){runOnUiThread(()->{toast("Account created. Sign in to continue.");login(false);});}});});}public void error(Exception ex){runOnUiThread(()->{create.setEnabled(true);toast(message(ex));});}});});}

    private void account(){if(!api.loggedIn()){login(false);return;}shell("My account");add(h1("Passenger profile"));add(small("Your NBC account QR identifies you as a passenger. It is not a boarding ticket."));api.call("/api/nbc/v1/account/me",new JSONObject(),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONObject q=r.optJSONObject("result"),source=q==null?r:q;JSONObject a=source.optJSONObject("account");if(a==null){cardResult("ACCOUNT UNAVAILABLE",source.optString("message",source.optString("error","Sign in again.")));return;}String number=a.optString("account_number","NBC account"),qr=a.optString("account_qr_value","");LinearLayout identity=card();identity.setGravity(Gravity.CENTER);TextView label=txt(number,21,NAVY);label.setTypeface(null,1);label.setGravity(Gravity.CENTER);identity.addView(label);if(!qr.isEmpty()){ImageView image=new ImageView(MainActivity.this);image.setImageBitmap(qrBitmap(qr,dp(210)));image.setScaleType(ImageView.ScaleType.FIT_CENTER);identity.addView(image,new LinearLayout.LayoutParams(-1,dp(225)));}identity.addView(small(a.optString("name")+"\n"+a.optString("email")+"\n"+a.optString("phone")));add(identity);Button edit=btn("Update name or phone",false);add(edit);edit.setOnClickListener(v->updateAccount(a.optString("name"),a.optString("phone")));});}public void error(Exception e){runOnUiThread(()->cardResult("ACCOUNT UNAVAILABLE",message(e)));}});}

    private void updateAccount(String currentName,String currentPhone){shell("Update account");add(h1("Passenger details"));EditText name=field("Full name"),phone=field("Mobile phone");name.setText(currentName);phone.setText(currentPhone);add(name);add(phone);Button save=btn("Save changes",true);add(save);save.setOnClickListener(v->api.call("/api/nbc/v1/account/update",payload("name",name.getText().toString().trim(),"phone",phone.getText().toString().trim()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->account());}public void error(Exception e){runOnUiThread(()->toast(message(e)));}}));}

    private Bitmap qrBitmap(String value,int size){try{BitMatrix matrix=new MultiFormatWriter().encode(value,BarcodeFormat.QR_CODE,size,size);Bitmap bitmap=Bitmap.createBitmap(size,size,Bitmap.Config.RGB_565);for(int y=0;y<size;y++)for(int x=0;x<size;x++)bitmap.setPixel(x,y,matrix.get(x,y)?NAVY:Color.WHITE);return bitmap;}catch(Exception e){return Bitmap.createBitmap(1,1,Bitmap.Config.RGB_565);}}

    private void cardResult(String title,String detail){
        LinearLayout c=card();TextView heading=txt(title,16,NAVY);heading.setTypeface(null,1);c.addView(heading);c.addView(small(detail));add(c);
    }

    private View routeSelector(String dot,String label,Spinner spinner,int color){
        LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),dp(5),dp(8),dp(5));row.setBackgroundResource(R.drawable.rounded_input);
        TextView marker=txt(dot,20,color);marker.setGravity(Gravity.CENTER);row.addView(marker,new LinearLayout.LayoutParams(dp(34),dp(54)));
        LinearLayout copy=box();TextView caption=txt(label,11,MUTED);caption.setTypeface(null,1);copy.addView(caption);spinner.setMinimumHeight(dp(42));copy.addView(spinner,new LinearLayout.LayoutParams(-1,dp(46)));row.addView(copy,new LinearLayout.LayoutParams(0,dp(72),1));
        return row;
    }

    private void passengerHome(){
        shell("NBC Traveler");add(h1("Where will you go?"));add(small("Search routes, reserve your seat, and travel across Belize."));
        LinearLayout search=card();Spinner from=new Spinner(this),to=new Spinner(this);search.addView(routeSelector("●","FROM",from,TEAL));TextView arrow=txt("↓",24,GOLD);arrow.setGravity(Gravity.CENTER);search.addView(arrow,new LinearLayout.LayoutParams(-1,dp(34)));search.addView(routeSelector("●","TO",to,Color.rgb(205,157,39)));gap(search);
        LinearLayout chips=new LinearLayout(this);EditText date=field("Today");date.setText("Today, "+new SimpleDateFormat("MMM d",Locale.US).format(new Date()));chips.addView(date,new LinearLayout.LayoutParams(0,dp(48),1));Space gap=new Space(this);chips.addView(gap,new LinearLayout.LayoutParams(dp(8),1));TextView passenger=txt("1 passenger",15,NAVY);passenger.setGravity(Gravity.CENTER);passenger.setBackgroundResource(R.drawable.rounded_input);chips.addView(passenger,new LinearLayout.LayoutParams(0,dp(48),1));search.addView(chips);gap(search);Button find=btn("Search trips  →",true);search.addView(find);add(search);TextView status=small("Loading active routes…");add(status);
        loadStops(from,to,status);find.setOnClickListener(v->{ArrayList<Integer> ids=(ArrayList<Integer>)from.getTag();if(ids==null||ids.isEmpty()){toast("Routes are still loading.");return;}tripResults(ids.get(from.getSelectedItemPosition()),ids.get(to.getSelectedItemPosition()),date.getText().toString());});
        add(h1("Upcoming trip"));if(api.loggedIn()){loadUpcoming();passengerQuickLinks();}else{LinearLayout sign=card();sign.addView(txt("Your upcoming tickets will appear here.",16,NAVY));Button b=btn("Sign in to view tickets",false);b.setOnClickListener(v->login(false));sign.addView(b);add(sign);}add(small("NBC Traveler v1.6.0 • API v9.12.0 • Secure booking and digital tickets"));
    }
    private void loadStops(Spinner from,Spinner to,TextView status){api.call("/api/nbc/v1/traveler/stops",new JSONObject(),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{try{JSONObject q=r.optJSONObject("result");JSONArray a=q==null?r.optJSONArray("stops"):q.optJSONArray("stops");ArrayList<String> names=new ArrayList<>();ArrayList<Integer> ids=new ArrayList<>();if(a!=null)for(int i=0;i<a.length();i++){JSONObject z=a.getJSONObject(i);names.add(z.optString("name"));ids.add(z.optInt("id"));}ArrayAdapter<String> ad=new ArrayAdapter<>(MainActivity.this,android.R.layout.simple_spinner_dropdown_item,names);from.setAdapter(ad);to.setAdapter(ad);from.setTag(ids);to.setTag(ids);status.setText(names.size()+" stops available");}catch(Exception e){status.setText("Could not load stops");}});}public void error(Exception e){runOnUiThread(()->status.setText("Offline • try again"));}});}
    private void loadUpcoming(){api.call("/api/nbc/v1/passenger/dashboard",new JSONObject(),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"tickets");if(a==null||a.length()==0){cardResult("NO UPCOMING TRIPS","Your next paid ticket will appear here.");return;}JSONObject t=a.optJSONObject(0);LinearLayout c=card();c.addView(txt(t.optString("run_number","NBC trip"),12,MUTED));TextView route=txt(ticketBoarding(t)+"  →  "+ticketDestination(t),18,NAVY);route.setTypeface(null,1);c.addView(route);c.addView(small(tripValue(t,"departure","Departure pending")+" • Seat "+t.optString("seat","—")));c.addView(txt(t.optString("state","TICKET").toUpperCase(Locale.US),12,TEAL));Button view=btn("View ticket",false);view.setOnClickListener(v->showTicket(t));c.addView(view);add(c);});}public void error(Exception e){runOnUiThread(()->cardResult("UPCOMING TRIP","Sign in again to refresh your dashboard."));}});}
    private void passengerQuickLinks(){add(h1("Travel wallet"));LinearLayout row=new LinearLayout(this);row.addView(quickAction("▣","Bookings",v->bookings()),new LinearLayout.LayoutParams(0,dp(80),1));row.addView(quickAction("▤","Bus Passes",v->passes()),new LinearLayout.LayoutParams(0,dp(80),1));row.addView(quickAction("$","Payments",v->payments()),new LinearLayout.LayoutParams(0,dp(80),1));add(row);}
    private JSONArray array(JSONObject r,String key){JSONObject q=r.optJSONObject("result");return q==null?r.optJSONArray(key):q.optJSONArray(key);}
    private void searchTrips(){shell("Trips");add(h1("Search trips"));add(small("Choose your route and travel date."));Spinner from=new Spinner(this),to=new Spinner(this);add(txt("FROM",12,TEAL));add(from);add(txt("TO",12,TEAL));add(to);EditText date=field("YYYY-MM-DD");date.setText(today());add(date);Button find=btn("Search available trips",true);add(find);TextView status=small("Loading stops…");add(status);loadStops(from,to,status);find.setOnClickListener(v->{ArrayList<Integer> ids=(ArrayList<Integer>)from.getTag();if(ids==null||ids.isEmpty()){toast("Routes are still loading.");return;}tripResults(ids.get(from.getSelectedItemPosition()),ids.get(to.getSelectedItemPosition()),date.getText().toString());});}
    private void tripResults(int origin,int destination,String date){api.call("/api/nbc/v1/traveler/search",payload("origin_id",origin,"destination_id",destination,"service_date",date),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{shell("Available trips");add(h1("Trips for your route"));JSONArray a=array(r,"trips");if(a==null||a.length()==0){cardResult("NO TRIPS FOUND","Try another route or travel date.");return;}for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);LinearLayout c=card();TextView route=txt(t.optString("route","NBC service"),19,NAVY);route.setTypeface(null,1);c.addView(route);c.addView(small(t.optString("departure")+"  →  "+t.optString("arrival")));c.addView(txt(t.optInt("available_seats")+" seats available     "+t.optString("currency","BZD")+" "+t.optDouble("fare"),15,TEAL));Button b=btn("View fare and seats",true);int id=t.optInt("trip_id");b.setOnClickListener(v->{if(api.loggedIn())booking(id,origin,destination);else login(false);});c.addView(b);add(c);}});}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}
    private void booking(int trip,int origin,int destination){shell("Review journey");add(h1("Fare and seat availability"));add(small("NBC confirms the fare and available seats directly from the server."));LinearLayout quote=card();quote.addView(small("Loading current fare and seats…"));add(quote);api.call("/api/nbc/v1/mobile/quote",payload("trip_id",trip,"origin_id",origin,"destination_id",destination,"passenger_type","adult","passenger_count",1),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONObject q=resultObj(r);quote.removeAllViews();quote.addView(txt(q.optString("currency","BZD")+" "+q.optDouble("total",q.optDouble("fare_per_passenger")),24,NAVY));quote.addView(small(q.optInt("available_seats")+" seats currently available"));});}public void error(Exception e){runOnUiThread(()->quote.addView(small("Fare refresh unavailable: "+message(e))));}});api.call("/api/nbc/v1/mobile/seats",payload("trip_id",trip,"origin_id",origin,"destination_id",destination),new ApiClient.Callback(){public void done(JSONObject r){}public void error(Exception e){}});EditText name=field("Passenger name"),phone=field("Mobile phone");add(name);add(phone);Button create=btn("Create booking",true);add(create);create.setOnClickListener(v->{try{create.setEnabled(false);api.call("/api/nbc/booking/create",new JSONObject().put("trip_id",trip).put("origin_id",origin).put("destination_id",destination).put("passenger_count",1).put("passenger_name",name.getText().toString()).put("phone",phone.getText().toString()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{cardResult("BOOKING CREATED","Open Bookings to review the balance and continue to a supported payment provider.");});}public void error(Exception e){runOnUiThread(()->{create.setEnabled(true);toast(message(e));});}});}catch(Exception e){toast(message(e));}});}
    private String ticketBoarding(JSONObject t){return objectName(t,"boarding",t.optString("boarding","Boarding"));}
    private String ticketDestination(JSONObject t){return objectName(t,"destination",t.optString("destination","Destination"));}
    private void myTicket(){if(!api.loggedIn()){login(false);return;}api.call("/api/nbc/v1/passenger/tickets",payload("limit",20),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"tickets");if(a!=null&&a.length()>0)showTicket(a.optJSONObject(0));else{shell("My ticket");cardResult("NO TICKETS","Your tickets will appear here.");}});}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}
    private void myTrips(){if(!api.loggedIn()){login(false);return;}shell("My trips");add(h1("Your tickets"));add(small("Upcoming and previous NBC journeys linked to your passenger account."));api.call("/api/nbc/v1/passenger/tickets",payload("limit",200),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"tickets");if(a==null||a.length()==0){cardResult("NO TRIPS YET","Book a journey from Home and your tickets will appear here.");return;}for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);LinearLayout c=card();TextView route=txt(ticketBoarding(t)+"  →  "+ticketDestination(t),18,NAVY);route.setTypeface(null,1);c.addView(route);c.addView(small(tripValue(t,"departure","Departure pending")+" • Seat "+t.optString("seat","—")));c.addView(txt(t.optString("state","ticket").toUpperCase(Locale.US),12,TEAL));Button open=btn("Open boarding pass",false);open.setOnClickListener(v->showTicket(t));c.addView(open);add(c);}});}public void error(Exception e){runOnUiThread(()->cardResult("UNABLE TO LOAD TRIPS",message(e)));}});}
    private void showTicket(JSONObject t){shell("My ticket");LinearLayout c=tealCard();c.addView(txt("NATIONAL BUS COMPANY",11,Color.rgb(215,231,232)));TextView title=txt("Boarding pass",25,Color.WHITE);title.setTypeface(null,1);c.addView(title);add(c);add(txt("ROUTE",11,TEAL));TextView route=txt(ticketBoarding(t)+"  →  "+ticketDestination(t),19,NAVY);route.setTypeface(null,1);add(route);add(txt("DEPARTURE",11,TEAL));add(txt(tripValue(t,"departure","Upcoming service"),16,NAVY));JSONObject trip=t.optJSONObject("trip"),bus=trip==null?null:trip.optJSONObject("bus");if(bus!=null)add(small("Bus "+bus.optString("fleet_no",bus.optString("name","To be assigned"))+" • Run "+t.optString("run_number","—")));LinearLayout info=new LinearLayout(this);info.addView(infoCell("SEAT",t.optString("seat","—")),new LinearLayout.LayoutParams(0,-2,1));info.addView(infoCell("TICKET",t.optString("ticket_no","NBC ticket")),new LinearLayout.LayoutParams(0,-2,1));add(info);LinearLayout qr=card();qr.setGravity(Gravity.CENTER);String token=t.optString("qr_token",t.optString("ticket_no","NBC ticket"));ImageView qrImage=new ImageView(this);qrImage.setImageBitmap(qrBitmap(token,dp(210)));qrImage.setScaleType(ImageView.ScaleType.FIT_CENTER);qr.addView(qrImage,new LinearLayout.LayoutParams(-1,dp(220)));qr.addView(small("Show this ticket at boarding"));add(qr);LinearLayout state=card();state.setBackgroundColor(Color.rgb(229,246,240));state.addView(txt("✓  "+t.optString("state","Ticket ready").toUpperCase(Locale.US),16,TEAL));add(state);}
    private LinearLayout infoCell(String title,String value){LinearLayout x=box();x.addView(txt(title,11,TEAL));TextView v=txt(value,17,NAVY);v.setTypeface(null,1);x.addView(v);return x;}
    private void ticketStatus(){shell("Ticket status");add(h1("Verify your ticket"));add(small("Enter the NBC QR token or ticket number."));EditText code=field("NBCQR… or NBC-2026-…");add(code);Button check=btn("Check ticket",true);add(check);check.setOnClickListener(v->{try{check.setEnabled(false);api.call("/api/nbc/v1/traveler/ticket_status",new JSONObject().put("token",code.getText().toString().trim()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{check.setEnabled(true);JSONObject q=r.optJSONObject("result");if(q!=null&&q.optJSONObject("ticket")!=null)showTicket(q.optJSONObject("ticket"));else cardResult("TICKET RESPONSE",r.toString());});}public void error(Exception e){runOnUiThread(()->{check.setEnabled(true);toast(message(e));});}});}catch(Exception e){toast(message(e));}});}
    private void board(){shell("Station boards");add(h1("Live station boards"));add(small("Choose a terminal and view current arrivals or departures."));Spinner station=new Spinner(this),mode=new Spinner(this);add(txt("TERMINAL",11,TEAL));add(station);add(txt("BOARD",11,TEAL));mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Departures","Arrivals","Both"}));add(mode);TextView status=small("Loading terminals…");add(status);Spinner unused=new Spinner(this);loadStops(station,unused,status);Button load=btn("View live board",true);add(load);load.setOnClickListener(v->{if(station.getSelectedItem()==null){toast("Select a terminal.");return;}String selectedMode=mode.getSelectedItem().toString().toLowerCase(Locale.US);try{api.call("/api/nbc/status_board",new JSONObject().put("terminal",station.getSelectedItem().toString()).put("mode",selectedMode).put("limit",120),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->renderBoard(r,selectedMode));}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}catch(Exception e){toast(message(e));}});}
    private void renderBoard(JSONObject r,String mode){shell("Station boards");add(h1(mode.substring(0,1).toUpperCase(Locale.US)+mode.substring(1)));JSONObject result=r.optJSONObject("result");JSONObject source=result==null?r:result;String terminal=source.optString("terminal","NBC terminal");add(small(terminal+" • Updated "+source.optString("generated_at","now")));JSONArray a=source.optJSONArray("trips");if(a==null||a.length()==0){cardResult("NO BOARD SERVICES","No "+mode+" are currently listed for this terminal.");return;}for(int i=0;i<a.length();i++){JSONObject z=a.optJSONObject(i);String boardTime=z.optString("actual","");if(boardTime.isEmpty()||"false".equalsIgnoreCase(boardTime))boardTime=z.optString("scheduled","—");LinearLayout c=card();TextView time=txt(boardTime,18,NAVY);time.setTypeface(null,1);c.addView(time);c.addView(small(z.optString("run_number","NBC run")));TextView route=txt(z.optString("origin")+"  →  "+z.optString("destination"),16,NAVY);route.setTypeface(null,1);c.addView(route);c.addView(txt(z.optString("status_label",z.optString("status","ON TIME")),13,TEAL));add(c);}}
    private void bookings(){if(!api.loggedIn()){login(false);return;}shell("Bookings");add(h1("Your bookings"));add(small("Bookings and balances are kept separate from issued travel tickets."));api.call("/api/nbc/v1/mobile/bookings",payload("limit",200),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"bookings");if(a==null||a.length()==0){cardResult("NO BOOKINGS","Search for a journey from Home to create a booking.");return;}for(int i=0;i<a.length();i++){JSONObject b=a.optJSONObject(i);LinearLayout c=card();TextView no=txt(b.optString("booking_no",b.optString("name","NBC booking")),18,NAVY);no.setTypeface(null,1);c.addView(no);c.addView(small(b.optString("state","draft").toUpperCase(Locale.US)+" • "+b.optInt("ticket_count")+" ticket(s)"));c.addView(txt(b.optString("currency","BZD")+" "+b.optDouble("total")+" • Balance "+b.optDouble("balance"),14,TEAL));add(c);}});}public void error(Exception e){runOnUiThread(()->cardResult("BOOKINGS UNAVAILABLE",message(e)));}});}
    private void payments(){if(!api.loggedIn()){login(false);return;}shell("Payments");add(h1("Payment history"));add(small("Payment status is confirmed by NBC and the selected payment provider."));api.call("/api/nbc/v1/mobile/payments",payload("limit",200),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"payments");if(a==null||a.length()==0){cardResult("NO PAYMENTS","Confirmed and pending payments will appear here.");return;}for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);LinearLayout c=card();TextView amount=txt(p.optString("currency","BZD")+" "+p.optDouble("amount"),20,NAVY);amount.setTypeface(null,1);c.addView(amount);c.addView(small(p.optString("method",p.optString("provider","Payment"))+" • "+p.optString("date","")));c.addView(txt(p.optString("state","pending").toUpperCase(Locale.US),12,TEAL));add(c);}});}public void error(Exception e){runOnUiThread(()->cardResult("PAYMENTS UNAVAILABLE",message(e)));}});}
    private void passes(){if(!api.loggedIn()){login(false);return;}shell("Bus Passes");add(h1("Your Bus Passes"));add(small("NBC validates pass dates, route coverage, payment state, and ride limits on the server."));Button buy=btn("Purchase a Bus Pass",true);buy.setOnClickListener(v->passTypes());add(buy);api.call("/api/nbc/v1/passenger/passes",new JSONObject(),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"passes");if(a==null||a.length()==0){cardResult("NO BUS PASSES","Choose Purchase a Bus Pass to view available products.");return;}for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);LinearLayout c=card();TextView name=txt(p.optString("type",p.optString("pass_no","NBC Bus Pass")),18,NAVY);name.setTypeface(null,1);c.addView(name);c.addView(small(p.optString("pass_no","")+" • "+p.optString("valid_from","—")+" to "+p.optString("valid_to","—")));c.addView(txt(p.optString("state","draft").toUpperCase(Locale.US)+" • "+p.optInt("rides_used")+" rides used",12,TEAL));Button open=btn("Open pass and QR",false);open.setOnClickListener(v->showPass(p));c.addView(open);add(c);}});}public void error(Exception e){runOnUiThread(()->cardResult("PASSES UNAVAILABLE",message(e)));}});}
    private void showPass(JSONObject p){shell("Bus Pass");LinearLayout hero=tealCard();hero.addView(txt("NBC BUS PASS",11,Color.WHITE));TextView no=txt(p.optString("pass_no","NBC Bus Pass"),22,Color.WHITE);no.setTypeface(null,1);hero.addView(no);hero.addView(txt(p.optString("state","draft").toUpperCase(Locale.US),13,Color.WHITE));add(hero);String qr=p.optString("qr_value","");if(!qr.isEmpty()){LinearLayout q=card();q.setGravity(Gravity.CENTER);ImageView image=new ImageView(this);image.setImageBitmap(qrBitmap(qr,dp(220)));q.addView(image,new LinearLayout.LayoutParams(-1,dp(230)));q.addView(small("Present this Bus Pass QR to authorized NBC staff"));add(q);}cardResult("PASS DETAILS",p.optString("valid_from","—")+" to "+p.optString("valid_to","—")+"\nPayment: "+p.optString("payment_state","pending")+"\nRides used: "+p.optInt("rides_used"));}
    private void passTypes(){shell("Purchase Bus Pass");add(h1("Choose a Bus Pass"));add(small("Prices and validity periods come directly from NBC. A new pass remains inactive until payment is confirmed."));api.call("/api/nbc/v1/passenger/pass_types",new JSONObject(),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"pass_types");if(a==null)a=array(r,"types");if(a==null||a.length()==0){cardResult("NO PASS PRODUCTS","No Bus Pass products are currently available.");return;}for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);LinearLayout c=card();TextView name=txt(p.optString("name","NBC Bus Pass"),18,NAVY);name.setTypeface(null,1);c.addView(name);c.addView(small(p.optInt("duration_days")+" days • "+p.optString("currency","BZD")+" "+p.optDouble("price")));Button purchase=btn("Create pass purchase",true);int id=p.optInt("id");purchase.setOnClickListener(v->purchasePass(id));c.addView(purchase);add(c);}});}public void error(Exception e){runOnUiThread(()->cardResult("PASS PRODUCTS UNAVAILABLE",message(e)));}});}
    private void purchasePass(int typeId){api.call("/api/nbc/v1/passenger/pass/purchase",payload("pass_type_id",typeId,"valid_from",today()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONObject source=resultObj(r);if(!source.optBoolean("ok",true)){toast(source.optString("message","Pass could not be created."));return;}shell("Bus Pass created");add(h1("Complete payment to activate"));cardResult("PASS CREATED","The pass is draft/unpaid. Open Payments or your provider flow and rely on NBC’s server-confirmed payment state before travel.");Button list=btn("View my Bus Passes",true);list.setOnClickListener(v->passes());add(list);});}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}
    private void operationsHome(){shell("Operations");add(txt("Good afternoon",25,NAVY));add(small("Your tools are matched to the NBC roles assigned to this account."));loadRunHero();add(txt("Quick actions",20,NAVY));LinearLayout quick=new LinearLayout(this);quick.setGravity(Gravity.CENTER);quick.addView(quickAction("□","Scan ticket",v->scan()),new LinearLayout.LayoutParams(0,dp(85),1));quick.addView(quickAction("▤","Validate pass",v->validatePass()),new LinearLayout.LayoutParams(0,dp(85),1));quick.addView(quickAction("⌖","Live GPS",v->gps()),new LinearLayout.LayoutParams(0,dp(85),1));add(quick);add(txt("Run progress",20,NAVY));progressCard();add(small("NBC Operations v1.6.0 • API v9.12.0"));}
    private View quickAction(String icon,String title,View.OnClickListener click){LinearLayout x=box();x.setGravity(Gravity.CENTER);TextView i=txt(icon,27,TEAL);i.setGravity(Gravity.CENTER);x.addView(i);TextView t=txt(title,12,NAVY);t.setGravity(Gravity.CENTER);x.addView(t);x.setOnClickListener(click);return x;}
    private void loadRunHero(){api.call("/api/nbc/v1/ops/my_runs",payload("service_date",today()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"runs");if(a==null||a.length()==0){cardResult("ASSIGNED RUN","No run is assigned yet.");return;}JSONObject z=a.optJSONObject(0);LinearLayout c=tealCard();c.addView(txt("ASSIGNED RUN",11,Color.rgb(215,231,232)));TextView no=txt(z.optString("run_number","NBC RUN"),23,Color.WHITE);no.setTypeface(null,1);c.addView(no);c.addView(txt(z.optString("route","Today’s route"),15,Color.WHITE));c.addView(txt(z.optString("bus","Bus assigned")+" • "+z.optString("passenger_count","passengers"),13,Color.rgb(215,231,232)));TextView live=txt("LIVE TRACKING",11,TEAL);live.setGravity(Gravity.CENTER);live.setBackgroundColor(Color.WHITE);c.addView(live,new LinearLayout.LayoutParams(dp(124),dp(28)));add(c);});}public void error(Exception e){runOnUiThread(()->cardResult("ASSIGNED RUN","Unable to refresh run data."));}});}
    private void progressCard(){LinearLayout c=card();c.addView(progressRow("●","Belize City","DEPARTED",TEAL));c.addView(progressRow("○","Belmopan","UP NEXT",GOLD));add(c);}
    private View progressRow(String icon,String place,String state,int color){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(txt(icon,24,color),new LinearLayout.LayoutParams(dp(34),-2));TextView p=txt(place,15,NAVY);p.setTypeface(null,1);r.addView(p,new LinearLayout.LayoutParams(0,-2,1));TextView s=txt(state,11,state.equals("UP NEXT")?MUTED:TEAL);s.setTypeface(null,1);r.addView(s);return r;}
    private void runs(){shell("Assigned runs");add(h1("Today’s service"));add(small("Open a run for its trip details, stops, and ownership-scoped manifest."));api.call("/api/nbc/v1/ops/my_runs",payload("service_date",today()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"runs");if(a==null||a.length()==0){cardResult("NO ASSIGNED RUNS","No service is assigned for today.");return;}for(int i=0;i<a.length();i++){JSONObject z=a.optJSONObject(i);LinearLayout c=card();TextView no=txt(z.optString("run_number","NBC RUN"),19,NAVY);no.setTypeface(null,1);c.addView(no);c.addView(small(z.optString("route","Route pending")+"\n"+z.optString("departure","")+" • "+z.optString("bus","Bus pending")));Button open=btn("Open run details",true);int tripId=z.optInt("trip_id");open.setOnClickListener(v->runDetail(tripId));c.addView(open);add(c);}});}public void error(Exception e){runOnUiThread(()->cardResult("RUNS UNAVAILABLE",message(e)));}});}
    private void runDetail(int tripId){shell("Run detail");add(h1("Run and manifest"));api.call("/api/nbc/v1/ops/run",payload("trip_id",tripId),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONObject source=resultObj(r),trip=source.optJSONObject("trip");if(trip!=null)cardResult(trip.optString("run_number","NBC RUN"),trip.optString("route","Route")+"\n"+trip.optString("departure","")+" • "+trip.optString("bus","Bus pending"));JSONArray stops=source.optJSONArray("stops");if(stops!=null){add(h1("Stops"));for(int i=0;i<stops.length();i++){JSONObject s=stops.optJSONObject(i);cardResult((i+1)+". "+s.optString("name","Stop"),s.optString("scheduled",s.optString("time",""))+" • "+s.optString("state","scheduled"));}}JSONArray manifest=source.optJSONArray("manifest");if(manifest!=null){add(h1("Passenger manifest"));for(int i=0;i<manifest.length();i++){JSONObject m=manifest.optJSONObject(i);cardResult(m.optString("passenger",m.optString("name","Passenger")),"Seat "+m.optString("seat","—")+" • "+m.optString("ticket_no","")+" • "+m.optString("state",""));}}});}public void error(Exception e){runOnUiThread(()->cardResult("RUN DETAIL UNAVAILABLE",message(e)));}});}
    private void operationsMore(){shell("Operations tools");add(h1("More tools"));action("▤","Passenger manifest","Load run detail and passenger manifest.",v->manifest());action("▣","Validate Bus Pass","Validate and optionally consume a server-authorized ride.",v->validatePass());action("♙","Passenger account","Find a passenger using an NBC account number or account QR.",v->accountLookup());action("⌖","Live GPS","Start, review, or end live run tracking.",v->gps());action("▦","Station boards","View live NBC arrival and departure boards.",v->board());if(allowed("station_sales"))action("$","Station sale","Create an authorized station ticket sale.",v->stationSale());}
    private void accountLookup(){shell("Passenger account");add(h1("Find passenger"));add(small("Scan or enter an NBC account QR/account number. This identifies the passenger only; it is not a ticket."));EditText account=field("NBC-ACC-######## or NBCACC:...");add(account);Button find=btn("Find passenger",true);add(find);find.setOnClickListener(v->api.call("/api/nbc/v1/account/lookup",payload("account",account.getText().toString().trim()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONObject source=resultObj(r),a=source.optJSONObject("account");if(a==null){cardResult("ACCOUNT NOT FOUND",source.optString("message",source.optString("error","No matching passenger account.")));return;}shell("Passenger account");add(h1(a.optString("name","Passenger")));cardResult(a.optString("account_number","NBC account"),a.optString("email")+"\n"+a.optString("phone"));});}public void error(Exception e){runOnUiThread(()->toast(message(e)));}}));}
    private void scan(){shell("Scanner");add(h1("Boarding desk"));add(small("Scan QR codes with your device or enter the code manually."));EditText code=field("QR token, ticket number, or code");add(code);Button validate=btn("Validate passenger",true);add(validate);validate.setOnClickListener(v->{try{validate.setEnabled(false);api.call("/api/nbc/validate_ticket",new JSONObject().put("code",code.getText().toString()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{validate.setEnabled(true);cardResult("VALIDATION RESULT",r.toString());Button check=btn("Check in passenger",true);Button board=btn("Board passenger",false);add(check);add(board);check.setOnClickListener(x->apiAction("/api/nbc/checkin_ticket",code.getText().toString()));board.setOnClickListener(x->apiAction("/api/nbc/board_ticket",code.getText().toString()));});}public void error(Exception e){runOnUiThread(()->{validate.setEnabled(true);toast(message(e));});}});}catch(Exception e){toast(message(e));}});}
    private void validatePass(){if(!allowed("pass_scan")){toast("This account is not authorized to validate Bus Passes.");return;}shell("Validate Bus Pass");add(h1("Bus Pass validation"));add(small("NBC checks payment, dates, route coverage, and ride limits. The app never decides pass validity locally."));EditText code=field("NBCPASS: code or pass QR"),trip=field("Trip ID (optional)"),stop=field("Boarding stop ID (optional)");add(code);add(trip);add(stop);CheckBox consume=new CheckBox(this);consume.setText("Consume one ride after successful validation");consume.setTextColor(NAVY);add(consume);Button validate=btn("Validate with NBC",true);add(validate);validate.setOnClickListener(v->{JSONObject p=payload("code",code.getText().toString().trim(),"consume",consume.isChecked());try{if(!trip.getText().toString().trim().isEmpty())p.put("trip_id",Integer.parseInt(trip.getText().toString().trim()));if(!stop.getText().toString().trim().isEmpty())p.put("boarding_stop_id",Integer.parseInt(stop.getText().toString().trim()));}catch(Exception e){toast("Trip and stop IDs must be numbers.");return;}api.call("/api/nbc/v1/ops/pass/validate",p,new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONObject source=resultObj(r);cardResult(source.optBoolean("valid")?"PASS VALID":"PASS NOT VALID",source.optString("message",source.optString("code","NBC response")));});}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});});}
    private void stationSale(){if(!allowed("station_sales")){toast("This account is not authorized for station sales.");return;}shell("Station sale");add(h1("Authorized ticket sale"));add(small("NBC rechecks the selected trip segment and seats before completing the sale."));EditText trip=field("Trip ID"),origin=field("Origin stop ID"),destination=field("Destination stop ID"),passenger=field("Passenger name or account"),seat=field("Seat number(s), comma separated"),payment=field("Payment method: cash, card, or account");add(trip);add(origin);add(destination);add(passenger);add(seat);add(payment);Button sell=btn("Complete station sale",true);add(sell);sell.setOnClickListener(v->{try{JSONArray seats=new JSONArray();for(String s:seat.getText().toString().split(","))if(!s.trim().isEmpty())seats.put(s.trim());JSONObject p=payload("trip_id",Integer.parseInt(trip.getText().toString()),"origin_id",Integer.parseInt(origin.getText().toString()),"destination_id",Integer.parseInt(destination.getText().toString()),"passenger",passenger.getText().toString().trim(),"passenger_type","adult","passenger_count",1,"seat_numbers",seats,"payment_method",payment.getText().toString().trim());api.call("/api/nbc/v1/station/sell",p,new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->cardResult("SALE RESPONSE",resultObj(r).toString()));}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}catch(Exception e){toast("Enter valid trip, origin, and destination IDs.");}});}
    private void apiAction(String path,String code){try{api.call(path,new JSONObject().put("code",code),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->cardResult("ACTION COMPLETE",r.toString()));}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}catch(Exception e){toast(message(e));}}
    private void manifest(){shell("Manifest");add(h1("Passenger manifest"));EditText trip=field("Trip ID");add(trip);Button load=btn("Load run and manifest",true);add(load);load.setOnClickListener(v->{try{runDetail(Integer.parseInt(trip.getText().toString().trim()));}catch(Exception e){toast("Enter a valid Trip ID.");}});}
    private void gps(){shell("Live GPS");add(h1("Bus tracking"));add(small("Start or end tracking for an assigned run, or view all active NBC buses."));EditText trip=field("Trip ID or run number");add(trip);Button start=btn("Start live tracking",true),active=btn("View active tracked runs",false),end=btn("End live tracking",false);add(start);add(active);add(end);start.setOnClickListener(v->liveRunAction("/api/nbc/live/start_run",trip.getText().toString(),"LIVE TRACKING STARTED"));end.setOnClickListener(v->liveRunAction("/api/nbc/live/end_run",trip.getText().toString(),"LIVE TRACKING ENDED"));active.setOnClickListener(v->api.call("/api/nbc/live/active_runs",new JSONObject(),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{shell("Active buses");add(h1("Live tracked runs"));cardResult("ACTIVE RUNS",r.toString());});}public void error(Exception e){runOnUiThread(()->toast(message(e)));}}));}
    private void liveRunAction(String path,String value,String title){try{JSONObject p=new JSONObject();try{p.put("trip_id",Integer.parseInt(value));}catch(Exception e){p.put("run_number",value);}api.call(path,p,new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->cardResult(title,r.toString()));}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}catch(Exception e){toast(message(e));}}
}
