package bz.nationalbus.nbc;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Build;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowInsets;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private final int NAVY=Color.rgb(7,26,43), TEAL=Color.rgb(24,169,139), GOLD=Color.rgb(249,199,79), ICE=Color.rgb(244,248,248), MUTED=Color.rgb(91,107,120), LINE=Color.rgb(220,231,232);
    private ApiClient api; private LinearLayout content; private boolean ops;
    private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private LinearLayout box(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);return x;}
    private TextView txt(String s,float size,int color){TextView x=new TextView(this);x.setText(s);x.setTextSize(size);x.setTextColor(color);x.setPadding(0,dp(3),0,dp(3));return x;}
    private TextView h1(String s){TextView x=txt(s,25,NAVY);x.setTypeface(null,1);return x;}
    private TextView small(String s){return txt(s,14,MUTED);}
    private Button btn(String s,boolean primary){Button x=new Button(this);x.setText(s);x.setTextSize(14);x.setAllCaps(false);x.setTypeface(null,1);x.setTextColor(primary?Color.WHITE:TEAL);x.setMinHeight(dp(48));x.setPadding(dp(14),0,dp(14),0);x.setBackgroundResource(primary?R.drawable.primary_button:R.drawable.secondary_button);return x;}
    private EditText field(String hint){EditText x=new EditText(this);x.setHint(hint);x.setTextSize(16);x.setSingleLine(true);x.setTextColor(NAVY);x.setHintTextColor(MUTED);x.setBackgroundResource(R.drawable.rounded_input);x.setPadding(dp(14),0,dp(14),0);return x;}
    private void add(View x){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=dp(12);content.addView(x,p);}
    private void spacer(){Space x=new Space(this);content.addView(x,new LinearLayout.LayoutParams(1,dp(8)));}
    private LinearLayout card(){LinearLayout x=box();x.setPadding(dp(16),dp(14),dp(16),dp(14));x.setBackgroundResource(R.drawable.rounded_card);return x;}
    private LinearLayout tealCard(){LinearLayout x=box();x.setPadding(dp(16),dp(14),dp(16),dp(14));x.setBackgroundColor(TEAL);return x;}
    private void gap(LinearLayout x){Space s=new Space(this);x.addView(s,new LinearLayout.LayoutParams(1,dp(8)));}
    private String message(Exception e){return e==null||e.getMessage()==null?"Something went wrong":e.getMessage();}
    private void toast(String s){Toast.makeText(this,s==null?"Something went wrong":s,Toast.LENGTH_LONG).show();}
    private String today(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
    private JSONObject payload(Object... values){JSONObject p=new JSONObject();try{for(int i=0;i+1<values.length;i+=2)p.put(String.valueOf(values[i]),values[i+1]);}catch(Exception ignored){}return p;}

    @Override public void onCreate(Bundle b){super.onCreate(b);api=new ApiClient(this);ops=getPackageName().contains("operations");home();}
    private void shell(String title){
        LinearLayout root=box();root.setBackgroundColor(ICE);LinearLayout bar=box();bar.setPadding(dp(20),dp(12),dp(20),dp(16));bar.setBackgroundColor(NAVY);
        LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.nbc_logo);logo.setScaleType(ImageView.ScaleType.FIT_CENTER);row.addView(logo,new LinearLayout.LayoutParams(dp(48),dp(48)));
        LinearLayout names=box();TextView brand=txt("NATIONAL BUS",11,GOLD);brand.setTypeface(null,1);names.addView(brand);TextView page=txt(title,21,Color.WHITE);page.setTypeface(null,1);names.addView(page);row.addView(names,new LinearLayout.LayoutParams(0,-2,1));
        if(api.loggedIn()){Button out=btn("Sign out",false);out.setTextColor(Color.WHITE);out.setBackgroundColor(Color.TRANSPARENT);out.setOnClickListener(v->{api.logout();home();});row.addView(out,new LinearLayout.LayoutParams(dp(82),dp(44)));}bar.addView(row);root.addView(bar);
        ScrollView scroll=new ScrollView(this);content=box();content.setPadding(dp(20),dp(20),dp(20),dp(28));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=navBar();root.addView(nav,new LinearLayout.LayoutParams(-1,dp(70)));setContentView(root);
        root.setOnApplyWindowInsetsListener((v,insets)->{int bottom=Build.VERSION.SDK_INT>=30?insets.getInsets(WindowInsets.Type.navigationBars()).bottom:insets.getSystemWindowInsetBottom();nav.setPadding(dp(8),dp(5),dp(8),dp(5)+bottom);ViewGroup.LayoutParams lp=nav.getLayoutParams();lp.height=dp(70)+bottom;nav.setLayoutParams(lp);return insets;});root.requestApplyInsets();
    }
    private void authShell(boolean staff){
        LinearLayout root=box();root.setBackgroundColor(ICE);LinearLayout hero=box();hero.setGravity(Gravity.CENTER);hero.setPadding(dp(24),dp(18),dp(24),dp(20));hero.setBackgroundResource(R.drawable.login_hero);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.nbc_logo);logo.setScaleType(ImageView.ScaleType.FIT_CENTER);hero.addView(logo,new LinearLayout.LayoutParams(dp(116),dp(132)));TextView n=txt("NATIONAL BUS COMPANY",14,GOLD);n.setTypeface(null,1);n.setGravity(Gravity.CENTER);hero.addView(n);TextView m=txt(staff?"OPERATIONS PORTAL":"PASSENGER APP",12,Color.WHITE);m.setGravity(Gravity.CENTER);hero.addView(m);root.addView(hero,new LinearLayout.LayoutParams(-1,dp(250)));ScrollView scroll=new ScrollView(this);content=box();content.setPadding(dp(22),dp(22),dp(22),dp(24));content.setBackgroundResource(R.drawable.auth_panel);scroll.addView(content);LinearLayout.LayoutParams panel=new LinearLayout.LayoutParams(-1,0,1);panel.setMargins(dp(14),dp(-8),dp(14),dp(14));root.addView(scroll,panel);TextView foot=txt("Secure access to NBC services",12,MUTED);foot.setGravity(Gravity.CENTER);root.addView(foot,new LinearLayout.LayoutParams(-1,dp(30)));setContentView(root);
    }
    private LinearLayout navBar(){LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.TOP);nav.setPadding(dp(8),dp(5),dp(8),dp(5));nav.setBackgroundColor(Color.WHITE);String[] labels=ops?new String[]{"⌂\nDashboard","▤\nRuns","✓\nScanner","▣\nMore"}:new String[]{"⌂\nHome","▣\nTickets","⌕\nTrips","♙\nProfile"};View.OnClickListener[] clicks=ops?new View.OnClickListener[]{v->operationsHome(),v->runs(),v->scan(),v->manifest()}:new View.OnClickListener[]{v->passengerHome(),v->myTicket(),v->searchTrips(),v->login(false)};for(int i=0;i<labels.length;i++){Button b=btn(labels[i],false);b.setTextSize(12);b.setPadding(0,0,0,0);b.setTextColor(i==0?TEAL:MUTED);b.setBackgroundColor(Color.TRANSPARENT);b.setOnClickListener(clicks[i]);nav.addView(b,new LinearLayout.LayoutParams(0,dp(60),1));}return nav;}
    private void action(String icon,String title,String desc,View.OnClickListener click){LinearLayout c=card(),row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView i=txt(icon,25,TEAL);i.setGravity(Gravity.CENTER);row.addView(i,new LinearLayout.LayoutParams(dp(38),dp(42)));LinearLayout copy=box();TextView t=txt(title,17,NAVY);t.setTypeface(null,1);copy.addView(t);copy.addView(small(desc));row.addView(copy,new LinearLayout.LayoutParams(0,-2,1));c.addView(row);c.setOnClickListener(click);add(c);}
    private void home(){if(ops){if(api.loggedIn())operationsHome();else login(true);}else passengerHome();}

    private void login(boolean staff){
        authShell(staff);add(h1(staff?"Staff sign in":"Welcome back, traveler."));
        add(small(staff?"Sign in with your NBC operations account.":"Sign in to view tickets and continue a booking."));
        EditText user=field("Email or username");
        EditText password=field("Password");password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);
        add(user);add(password);Button submit=btn("Sign in securely",true);add(submit);
        submit.setOnClickListener(v->{
            String username=user.getText().toString().trim(),secret=password.getText().toString();
            if(username.isEmpty()||secret.isEmpty()){toast("Enter your username and password.");return;}
            submit.setEnabled(false);submit.setText("Signing in…");
            api.login(username,secret,new ApiClient.Callback(){
                public void done(JSONObject r){runOnUiThread(()->{
                    JSONObject result=r.optJSONObject("result");
                    if(result!=null&&result.optInt("uid",0)>0){home();return;}
                    submit.setEnabled(true);submit.setText("Sign in securely");toast("The username or password is incorrect.");
                });}
                public void error(Exception e){runOnUiThread(()->{submit.setEnabled(true);submit.setText("Sign in securely");toast(message(e));});}
            });
        });
    }

    private void cardResult(String title,String detail){
        LinearLayout c=card();TextView heading=txt(title,16,NAVY);heading.setTypeface(null,1);c.addView(heading);c.addView(small(detail));add(c);
    }

    private View routeSelector(String dot,String label,Spinner spinner,int color){
        LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),dp(5),dp(8),dp(5));row.setBackgroundResource(R.drawable.rounded_input);
        TextView marker=txt(dot,20,color);marker.setGravity(Gravity.CENTER);row.addView(marker,new LinearLayout.LayoutParams(dp(34),dp(54)));
        LinearLayout copy=box();TextView caption=txt(label,11,MUTED);caption.setTypeface(null,1);copy.addView(caption);spinner.setMinimumHeight(dp(42));copy.addView(spinner,new LinearLayout.LayoutParams(-1,dp(46)));row.addView(copy,new LinearLayout.LayoutParams(0,dp(72),1));
        return row;
    }

    private void passengerHome(){
        shell("NBC Traveler");add(h1("Where will you go?"));add(small("Book your next journey across Belize."));
        LinearLayout search=card();Spinner from=new Spinner(this),to=new Spinner(this);search.addView(routeSelector("●","FROM",from,TEAL));TextView arrow=txt("↓",24,GOLD);arrow.setGravity(Gravity.CENTER);search.addView(arrow,new LinearLayout.LayoutParams(-1,dp(34)));search.addView(routeSelector("●","TO",to,Color.rgb(205,157,39)));gap(search);
        LinearLayout chips=new LinearLayout(this);EditText date=field("Today");date.setText("Today, "+new SimpleDateFormat("MMM d",Locale.US).format(new Date()));chips.addView(date,new LinearLayout.LayoutParams(0,dp(48),1));Space gap=new Space(this);chips.addView(gap,new LinearLayout.LayoutParams(dp(8),1));TextView passenger=txt("1 passenger",15,NAVY);passenger.setGravity(Gravity.CENTER);passenger.setBackgroundResource(R.drawable.rounded_input);chips.addView(passenger,new LinearLayout.LayoutParams(0,dp(48),1));search.addView(chips);gap(search);Button find=btn("Search trips  →",true);search.addView(find);add(search);TextView status=small("Loading active routes…");add(status);
        loadStops(from,to,status);find.setOnClickListener(v->{ArrayList<Integer> ids=(ArrayList<Integer>)from.getTag();if(ids==null||ids.isEmpty()){toast("Routes are still loading.");return;}tripResults(ids.get(from.getSelectedItemPosition()),ids.get(to.getSelectedItemPosition()),date.getText().toString());});
        add(h1("Upcoming trip"));if(api.loggedIn())loadUpcoming();else{LinearLayout sign=card();sign.addView(txt("Your upcoming tickets will appear here.",16,NAVY));Button b=btn("Sign in to view tickets",false);b.setOnClickListener(v->login(false));sign.addView(b);add(sign);}add(small("NBC Traveler v1.4 • Secure booking and digital tickets"));
    }
    private void loadStops(Spinner from,Spinner to,TextView status){api.call("/api/nbc/v1/traveler/stops",new JSONObject(),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{try{JSONObject q=r.optJSONObject("result");JSONArray a=q==null?r.optJSONArray("stops"):q.optJSONArray("stops");ArrayList<String> names=new ArrayList<>();ArrayList<Integer> ids=new ArrayList<>();if(a!=null)for(int i=0;i<a.length();i++){JSONObject z=a.getJSONObject(i);names.add(z.optString("name"));ids.add(z.optInt("id"));}ArrayAdapter<String> ad=new ArrayAdapter<>(MainActivity.this,android.R.layout.simple_spinner_dropdown_item,names);from.setAdapter(ad);to.setAdapter(ad);from.setTag(ids);to.setTag(ids);status.setText(names.size()+" stops available");}catch(Exception e){status.setText("Could not load stops");}});}public void error(Exception e){runOnUiThread(()->status.setText("Offline • try again"));}});}
    private void loadUpcoming(){api.call("/api/nbc/v1/traveler/my_tickets",new JSONObject(),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"tickets");if(a==null||a.length()==0){cardResult("NO UPCOMING TRIPS","Your next paid ticket will appear here.");return;}JSONObject t=a.optJSONObject(0);LinearLayout c=card();c.addView(txt(t.optString("run_number","NBC trip"),12,MUTED));TextView route=txt(t.optString("boarding")+"  →  "+t.optString("destination"),18,NAVY);route.setTypeface(null,1);c.addView(route);c.addView(small(t.optString("departure")+" • Seat "+t.optString("seat","—")));c.addView(txt("PAID",12,TEAL));Button view=btn("View ticket",false);view.setOnClickListener(v->showTicket(t));c.addView(view);add(c);});}public void error(Exception e){runOnUiThread(()->cardResult("UPCOMING TRIP","Sign in again to refresh your tickets."));}});}
    private JSONArray array(JSONObject r,String key){JSONObject q=r.optJSONObject("result");return q==null?r.optJSONArray(key):q.optJSONArray(key);}
    private void searchTrips(){shell("Trips");add(h1("Search trips"));add(small("Choose your route and travel date."));Spinner from=new Spinner(this),to=new Spinner(this);add(txt("FROM",12,TEAL));add(from);add(txt("TO",12,TEAL));add(to);EditText date=field("YYYY-MM-DD");date.setText(today());add(date);Button find=btn("Search available trips",true);add(find);TextView status=small("Loading stops…");add(status);loadStops(from,to,status);find.setOnClickListener(v->{ArrayList<Integer> ids=(ArrayList<Integer>)from.getTag();if(ids==null||ids.isEmpty()){toast("Routes are still loading.");return;}tripResults(ids.get(from.getSelectedItemPosition()),ids.get(to.getSelectedItemPosition()),date.getText().toString());});}
    private void tripResults(int origin,int destination,String date){api.call("/api/nbc/v1/traveler/search",payload("origin_id",origin,"destination_id",destination,"service_date",date),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{shell("Available trips");add(h1("Trips for your route"));JSONArray a=array(r,"trips");if(a==null||a.length()==0){cardResult("NO TRIPS FOUND","Try another route or travel date.");return;}for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);LinearLayout c=card();TextView route=txt(t.optString("route","NBC service"),19,NAVY);route.setTypeface(null,1);c.addView(route);c.addView(small(t.optString("departure")+"  →  "+t.optString("arrival")));c.addView(txt(t.optInt("available_seats")+" seats available     BZ$"+t.optDouble("fare"),15,TEAL));Button b=btn("Select this trip",true);int id=t.optInt("trip_id");b.setOnClickListener(v->{if(api.loggedIn())booking(id);else login(false);});c.addView(b);add(c);}});}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}
    private void booking(int trip){shell("Passenger details");add(h1("Who is traveling?"));add(small("We’ll use these details to prepare your ticket."));EditText name=field("Passenger name"),phone=field("Mobile phone");add(name);add(phone);Button create=btn("Create booking",true);add(create);create.setOnClickListener(v->{try{create.setEnabled(false);api.call("/api/nbc/booking/create",new JSONObject().put("trip_id",trip).put("passenger_count",1).put("passenger_name",name.getText().toString()).put("phone",phone.getText().toString()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->cardResult("BOOKING CREATED","Continue to payment from the booking details."));}public void error(Exception e){runOnUiThread(()->{create.setEnabled(true);toast(message(e));});}});}catch(Exception e){toast(message(e));}});}
    private void myTicket(){if(!api.loggedIn()){login(false);return;}api.call("/api/nbc/v1/traveler/my_tickets",new JSONObject(),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"tickets");if(a!=null&&a.length()>0)showTicket(a.optJSONObject(0));else{shell("My ticket");cardResult("NO TICKETS","Your paid tickets will appear here.");}});}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}
    private void showTicket(JSONObject t){shell("My ticket");LinearLayout c=tealCard();c.addView(txt("NATIONAL BUS COMPANY",11,Color.rgb(215,231,232)));TextView title=txt("Boarding pass",25,Color.WHITE);title.setTypeface(null,1);c.addView(title);add(c);add(txt("ROUTE",11,TEAL));TextView route=txt(t.optString("boarding")+"  →  "+t.optString("destination"),19,NAVY);route.setTypeface(null,1);add(route);add(txt("DEPARTURE",11,TEAL));add(txt(t.optString("departure","Upcoming service"),16,NAVY));LinearLayout info=new LinearLayout(this);info.addView(infoCell("SEAT",t.optString("seat","—")),new LinearLayout.LayoutParams(0,-2,1));info.addView(infoCell("TICKET",t.optString("ticket_no","NBC ticket")),new LinearLayout.LayoutParams(0,-2,1));add(info);LinearLayout qr=card();qr.setGravity(Gravity.CENTER);qr.addView(txt("▦",92,NAVY));qr.addView(small("Show this ticket at boarding"));add(qr);LinearLayout paid=card();paid.setBackgroundColor(Color.rgb(229,246,240));paid.addView(txt("✓  Paid and ready to board",16,TEAL));add(paid);}
    private LinearLayout infoCell(String title,String value){LinearLayout x=box();x.addView(txt(title,11,TEAL));TextView v=txt(value,17,NAVY);v.setTypeface(null,1);x.addView(v);return x;}
    private void ticketStatus(){shell("Ticket status");add(h1("Verify your ticket"));add(small("Enter the NBC QR token or ticket number."));EditText code=field("NBCQR… or NBC-2026-…");add(code);Button check=btn("Check ticket",true);add(check);check.setOnClickListener(v->{try{check.setEnabled(false);api.call("/api/nbc/v1/traveler/ticket_status",new JSONObject().put("token",code.getText().toString().trim()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{check.setEnabled(true);JSONObject q=r.optJSONObject("result");if(q!=null&&q.optJSONObject("ticket")!=null)showTicket(q.optJSONObject("ticket"));else cardResult("TICKET RESPONSE",r.toString());});}public void error(Exception e){runOnUiThread(()->{check.setEnabled(true);toast(message(e));});}});}catch(Exception e){toast(message(e));}});}
    private void board(){shell("Station board");add(h1("Departures"));add(small("Live status from NBC operations."));EditText station=field("Station or terminal, e.g. Belize City");add(station);Button load=btn("Refresh board",true);add(load);load.setOnClickListener(v->{try{api.call("/api/nbc/status_board",new JSONObject().put("station",station.getText().toString()).put("mode","departures").put("limit",50),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->renderBoard(r));}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}catch(Exception e){toast(message(e));}});}
    private void renderBoard(JSONObject r){shell("Station board");add(h1("Departures"));JSONArray a=array(r,"trips");if(a==null||a.length()==0){cardResult("NO DEPARTURES","No departures are currently listed.");return;}for(int i=0;i<a.length();i++){JSONObject z=a.optJSONObject(i);LinearLayout c=card();TextView time=txt(z.optString("scheduled","—"),18,NAVY);time.setTypeface(null,1);c.addView(time);c.addView(small(z.optString("origin")+"  →  "+z.optString("destination")));c.addView(txt(z.optString("status_label",z.optString("status","ON TIME")),13,TEAL));add(c);}}
    private void operationsHome(){shell("Operations");add(txt("Good afternoon",25,NAVY));add(small("Here is your run for today."));loadRunHero();add(txt("Quick actions",20,NAVY));LinearLayout quick=new LinearLayout(this);quick.setGravity(Gravity.CENTER);quick.addView(quickAction("□","Scan ticket",v->scan()),new LinearLayout.LayoutParams(0,dp(85),1));quick.addView(quickAction("＋","Sell ticket",v->manifest()),new LinearLayout.LayoutParams(0,dp(85),1));add(quick);add(txt("Run progress",20,NAVY));progressCard();}
    private View quickAction(String icon,String title,View.OnClickListener click){LinearLayout x=box();x.setGravity(Gravity.CENTER);TextView i=txt(icon,27,TEAL);i.setGravity(Gravity.CENTER);x.addView(i);TextView t=txt(title,12,NAVY);t.setGravity(Gravity.CENTER);x.addView(t);x.setOnClickListener(click);return x;}
    private void loadRunHero(){api.call("/api/nbc/v1/ops/my_runs",payload("service_date",today()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{JSONArray a=array(r,"runs");if(a==null||a.length()==0){cardResult("ASSIGNED RUN","No run is assigned yet.");return;}JSONObject z=a.optJSONObject(0);LinearLayout c=tealCard();c.addView(txt("ASSIGNED RUN",11,Color.rgb(215,231,232)));TextView no=txt(z.optString("run_number","NBC RUN"),23,Color.WHITE);no.setTypeface(null,1);c.addView(no);c.addView(txt(z.optString("route","Today’s route"),15,Color.WHITE));c.addView(txt(z.optString("bus","Bus assigned")+" • "+z.optString("passenger_count","passengers"),13,Color.rgb(215,231,232)));TextView live=txt("LIVE TRACKING",11,TEAL);live.setGravity(Gravity.CENTER);live.setBackgroundColor(Color.WHITE);c.addView(live,new LinearLayout.LayoutParams(dp(124),dp(28)));add(c);});}public void error(Exception e){runOnUiThread(()->cardResult("ASSIGNED RUN","Unable to refresh run data."));}});}
    private void progressCard(){LinearLayout c=card();c.addView(progressRow("●","Belize City","DEPARTED",TEAL));c.addView(progressRow("○","Belmopan","UP NEXT",GOLD));add(c);}
    private View progressRow(String icon,String place,String state,int color){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(txt(icon,24,color),new LinearLayout.LayoutParams(dp(34),-2));TextView p=txt(place,15,NAVY);p.setTypeface(null,1);r.addView(p,new LinearLayout.LayoutParams(0,-2,1));TextView s=txt(state,11,state.equals("UP NEXT")?MUTED:TEAL);s.setTypeface(null,1);r.addView(s);return r;}
    private void runs(){shell("Assigned runs");add(h1("Today’s service"));loadRunHero();}
    private void scan(){shell("Scanner");add(h1("Boarding desk"));add(small("Scan QR codes with your device or enter the code manually."));EditText code=field("QR token, ticket number, or code");add(code);Button validate=btn("Validate passenger",true);add(validate);validate.setOnClickListener(v->{try{validate.setEnabled(false);api.call("/api/nbc/validate_ticket",new JSONObject().put("code",code.getText().toString()),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->{validate.setEnabled(true);cardResult("VALIDATION RESULT",r.toString());Button check=btn("Check in passenger",true);Button board=btn("Board passenger",false);add(check);add(board);check.setOnClickListener(x->apiAction("/api/nbc/checkin_ticket",code.getText().toString()));board.setOnClickListener(x->apiAction("/api/nbc/board_ticket",code.getText().toString()));});}public void error(Exception e){runOnUiThread(()->{validate.setEnabled(true);toast(message(e));});}});}catch(Exception e){toast(message(e));}});}
    private void apiAction(String path,String code){try{api.call(path,new JSONObject().put("code",code),new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->cardResult("ACTION COMPLETE",r.toString()));}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}catch(Exception e){toast(message(e));}}
    private void manifest(){shell("Manifest");add(h1("Passenger manifest"));EditText trip=field("Trip ID or run number");add(trip);Button load=btn("Load manifest",true);add(load);load.setOnClickListener(v->{try{JSONObject p=new JSONObject();String val=trip.getText().toString();try{p.put("trip_id",Integer.parseInt(val));}catch(Exception e){p.put("run_number",val);}api.call("/api/nbc/manifest",p,new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->cardResult("MANIFEST",r.toString()));}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}catch(Exception e){toast(message(e));}});}
    private void gps(){shell("Live GPS");add(h1("Start a live run"));add(small("Send the bus run identifier to begin live tracking."));EditText trip=field("Trip ID or run number");add(trip);Button start=btn("Start live tracking",true);add(start);start.setOnClickListener(v->{try{JSONObject p=new JSONObject();String val=trip.getText().toString();try{p.put("trip_id",Integer.parseInt(val));}catch(Exception e){p.put("run_number",val);}api.call("/api/nbc/live/start_run",p,new ApiClient.Callback(){public void done(JSONObject r){runOnUiThread(()->cardResult("LIVE TRACKING STARTED",r.toString()));}public void error(Exception e){runOnUiThread(()->toast(message(e)));}});}catch(Exception e){toast(message(e));}});}
}
