apply plugin: 'com.android.application'

android { namespace 'bz.nationalbus.nbc'; compileSdk 35
    defaultConfig { applicationId 'bz.nationalbus.nbc'; minSdk 26; targetSdk 35; versionCode 177; versionName '1.7.7' }
    flavorDimensions += 'edition'
    productFlavors {
        passenger { dimension 'edition'; applicationIdSuffix '.passenger'; versionNameSuffix '-passenger' }
        operations { dimension 'edition'; applicationIdSuffix '.operations'; versionNameSuffix '-operations' }
    }
    buildTypes { release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
}
